### ISSUE TITLE
error on building bride package with two nodes

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/bride#59] opened 2014-05-09 15:11 UTC
Error message:
CMake Error at /opt/ros/hydro/share/dynamic_reconfigure/cmake/extras.cmake:60 (add_custom_target):
  add_custom_target cannot create target "test_aub_gencfg" because another
  target with the same name already exists.  The existing target is a custom
  target created in source directory "/home/fmw/git/care-o-bot/src/test_aub".
  See documentation for policy CMP0002 for more details.
Call Stack (most recent call first):
  test_aub/CMakeLists.txt:20 (generate_dynamic_reconfigure_options)

CMakeLists.txt looks like:
generate_dynamic_reconfigure_options(cfg/node1.cfg)
generate_dynamic_reconfigure_options(cfg/node2.cfg)

and should probably be:
generate_dynamic_reconfigure_options(cfg/node1.cfg cfg/node2.cfg)

**Comment by abubeck** [comment] 2014-05-09 16:15
Duplicate of #24

**Closed as completed by abubeck** 2014-05-09 16:15 UTC
Labels: bug
