### ISSUE TITLE
capability editor: add property to fill limits for parameters

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/bride#94] opened 2014-07-18 07:32 UTC
in BRIDE 0.3.3 it is only possible to specify the default value, but the range limits e.g. for a parameter of type int is fixed to -100 to +100.
`gen.add("timeout", int_t, 0, "Autogenerated parameter based on model.", , -100, 100)`

Should be handled for all type of parameters (int, double, string, int, bool, XmlRpcValue).

**Comment by abubeck** [comment] 2014-07-18 12:24
Duplicate of #92 .

**Closed as completed by abubeck** 2014-07-18 12:24 UTC
Labels: enhancement
