### ISSUE TITLE
Node updates not properly working after code creation

### ISSUE THREAD

**Issue by ipa-jsf** [ipa320/bride#36] opened 2014-03-31 10:37 UTC
Once BRIDE has generated the C++ source code and you change the node name afterwards, BRIDE does not update all necessary files where the node name appears. Instead, one has to manually delete all files and then do a rebuild with bride

**Comment by abubeck** [comment] 2014-06-13 07:57
I cannot reproduce this. When changing the node name all files are updated correctly.
Was this maybe a problem with an old version? I will close this issue, if you still have the problem or can help to reproduce the problem feel free to open it again.

**Closed as completed by abubeck** 2014-06-13 07:57 UTC
